default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: ggig
  username: root
  password: 
  socket: /tmp/mysql.sock
  host: localhost

development:
  <<: *default


test:
  <<: *default

production:
  <<: *default
  username: GGIG
  password: <%= ENV['GGIG_DATABASE_PASSWORD'] %>
