default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: ggie
  username: ggie
  password: dz7xCmbEJV
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

development:
  <<: *default


test:
  <<: *default

production:
  <<: *default
